#include<bits/stdc++.h>

using namespace std;

int main() {
    // int arry[57];
    // char arry[106];
    // bool arry[23];
    // int arr[]={1 ,3,5,7,9 };
    // for(int i=0;i<5;i++){
    //     cout<<arr[i]<<" ";
    // }
    // int arr[10];
    // cout<<"enter"<<endl;
    // for(int i=0;i<10;i++){
    //     int n;
    //     cin>>n;
    //     arr[i]=n;
    // }
    // for(int i=0;i<10;i++){
    //     cout<<arr[i]<<" ";
    // }
    int arr[5]={  };
        // memset(arr,2,sizeof(arr));
    for(int i=0;i<5;i++){
        arr[i]=23;
    }   
    for(int i=0;i<5;i++){
        cout<<arr[i];
    } 
    
    return 0;
}